/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TextSection = {
  _type: "textSection";
  label?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageGallery = {
  _type: "imageGallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  layout?: "grid" | "pairs";
  framing?: "wide" | "square" | "tall" | "natural";
};

export type FeatureImage = {
  _type: "featureImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type ProjectCredit = {
  _type: "projectCredit";
  name?: string;
  note?: string;
  kind?: "won" | "award" | "detail";
};

export type HomeCard = {
  _type: "homeCard";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  text?: string;
};

export type HomeGallery = {
  _type: "homeGallery";
  heading?: string;
  lead?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  button?: string;
};

export type HeroSlide = {
  _type: "heroSlide";
  caption?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  background?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sortOrder?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shortTitle?: string;
  slug?: Slug;
  sortOrder?: number;
  context?: string;
  year?: number;
  lead?: string;
  credits?: Array<
    {
      _key: string;
    } & ProjectCredit
  >;
  portfolio?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  portfolioUrl?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: Array<
    | ({
        _key: string;
      } & FeatureImage)
    | ({
        _key: string;
      } & ImageGallery)
    | ({
        _key: string;
      } & TextSection)
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TermsPage = {
  _id: string;
  _type: "termsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    heading?: string;
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    heading?: string;
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type BookPage = {
  _id: string;
  _type: "bookPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    heading?: string;
    lead?: string;
  };
  overview?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  inside?: {
    heading?: string;
  };
  atlas?: {
    caption?: string;
    primaryButton?: string;
    secondaryButton?: string;
  };
};

export type CourseSketchbookPage = {
  _id: string;
  _type: "courseSketchbookPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    heading?: string;
    lead?: string;
  };
  overview?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  details?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type CourseCommunicationPage = {
  _id: string;
  _type: "courseCommunicationPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    heading?: string;
    lead?: string;
  };
  overview?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  details?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type ProductPage = {
  _id: string;
  _type: "productPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    heading?: string;
    lead?: string;
  };
  overview?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  details?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type ShopPage = {
  _id: string;
  _type: "shopPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    label?: string;
    heading?: string;
    lead?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    primaryButton?: string;
    secondaryButton?: string;
  };
  catalogue?: {
    label?: string;
    heading?: string;
  };
  testimonials?: {
    heading?: string;
    lead?: string;
  };
  faq?: {
    label?: string;
    heading?: string;
    note?: string;
    helpHeading?: string;
    helpLead?: string;
    helpButton?: string;
  };
};

export type PartnersArchivePage = {
  _id: string;
  _type: "partnersArchivePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: {
    heading?: string;
    lead?: string;
  };
};

export type PartnersPage = {
  _id: string;
  _type: "partnersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: {
    heading?: string;
    lead?: string;
    button?: string;
  };
  clients?: {
    label?: string;
    heading?: string;
    note?: string;
  };
  statement?: {
    heading?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    lead?: string;
    button?: string;
  };
  services?: {
    label?: string;
    lead?: string;
  };
  results?: {
    label?: string;
    heading?: string;
    note?: string;
  };
  enquire?: {
    label?: string;
    heading?: string;
    lead?: string;
  };
};

export type InfluencePage = {
  _id: string;
  _type: "influencePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    label?: string;
    heading?: string;
    lead?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  reach?: {
    label?: string;
    number?: string;
    text?: string;
  };
  approach?: {
    label?: string;
    statement?: string;
  };
  origins?: {
    label?: string;
    heading?: string;
  };
  insights?: {
    label?: string;
    heading?: string;
    lead?: string;
  };
  atlas?: {
    label?: string;
    heading?: string;
  };
  book?: {
    label?: string;
    heading?: string;
    lead?: string;
    button?: string;
  };
};

export type ArchitecturePage = {
  _id: string;
  _type: "architecturePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    label?: string;
    heading?: string;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    headline?: string;
    slides?: Array<
      {
        _key: string;
      } & HeroSlide
    >;
    primaryButton?: string;
    secondaryButton?: string;
  };
  logoWall?: {
    label?: string;
  };
  practice?: {
    label?: string;
    statement?: string;
  };
  slider?: {
    images?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }>;
  };
  recognition?: {
    label?: string;
    heading?: string;
    lead?: string;
    button?: string;
    cards?: Array<
      {
        _key: string;
      } & HomeCard
    >;
  };
  influence?: HomeGallery;
  partners?: HomeGallery;
  projects?: HomeGallery;
  courses?: HomeGallery;
  getInTouch?: {
    label?: string;
    title?: string;
    portrait?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    lead?: string;
    button?: string;
  };
};

export type SanityVercelProtectionBypass = {
  _id: string;
  _type: "sanity.vercelProtectionBypass";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  secret?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TextSection
  | SanityImageAssetReference
  | ImageGallery
  | FeatureImage
  | ProjectCredit
  | HomeCard
  | HomeGallery
  | HeroSlide
  | Client
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | Project
  | Slug
  | TermsPage
  | PrivacyPage
  | BookPage
  | CourseSketchbookPage
  | CourseCommunicationPage
  | ProductPage
  | ShopPage
  | PartnersArchivePage
  | PartnersPage
  | InfluencePage
  | ArchitecturePage
  | HomePage
  | SanityVercelProtectionBypass
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: PROJECT_INDEX_QUERY
// Query: *[_type == "project" && string::startsWith(_id, "live-") == $live && defined(slug.current)] | order(sortOrder asc, _createdAt asc) {  _id,  "name": coalesce(shortTitle, title),  "slug": slug.current,  context,  year,  coverImage { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }}
export type PROJECT_INDEX_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  context: string | null;
  year: number | null;
  coverImage: {
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
  } | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: PROJECT_PAGE_QUERY
// Query: *[_type == "project" && string::startsWith(_id, "live-") == $live && slug.current == $slug][0] {  _id,  title,  "name": coalesce(shortTitle, title),  "slug": slug.current,  context,  year,  lead,  credits[]{ _key, name, note, kind },  "portfolioUrl": coalesce(portfolio.asset->url, portfolioUrl),  content[]{    _key,    _type,    _type == "featureImage" => { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },    _type == "imageGallery" => { layout, framing, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },    _type == "textSection" => { label, body }  }}
export type PROJECT_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  name: string | null;
  slug: string | null;
  context: string | null;
  year: number | null;
  lead: string | null;
  credits: Array<{
    _key: string;
    name: string | null;
    note: string | null;
    kind: "award" | "detail" | "won" | null;
  }> | null;
  portfolioUrl: string | null;
  content: Array<
    | {
        _key: string;
        _type: "featureImage";
        asset: {
          _id: string;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
      }
    | {
        _key: string;
        _type: "imageGallery";
        layout: "grid" | "pairs" | null;
        framing: "natural" | "square" | "tall" | "wide" | null;
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "textSection";
        label: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
  > | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: CLIENT_LOGOS_QUERY
// Query: *[_type == "client" && string::startsWith(_id, "live-") == $live && defined(logo.asset)] | order(sortOrder asc, name asc) {  _id,  name,  logo { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot }}
export type CLIENT_LOGOS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  logo: {
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == select($live => "live-homePage", "homePage")][0] {  hero {    headline,    slides[]{ _key, caption, photo { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot }, background { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot } },    primaryButton,    secondaryButton  },  logoWall { label },  practice { label, statement },  slider { images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },  recognition { label, heading, lead, button, cards[]{ _key, title, text, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } } },  influence { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button },  partners { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button },  projects { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button },  courses { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button }}
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      logoWall: null;
      practice: null;
      slider: null;
      recognition: null;
      influence: null;
      partners: null;
      projects: null;
      courses: null;
    }
  | {
      hero: {
        headline: null;
        slides: null;
        primaryButton: null;
        secondaryButton: null;
      } | null;
      logoWall: null;
      practice: null;
      slider: null;
      recognition: null;
      influence: null;
      partners: null;
      projects: null;
      courses: null;
    }
  | {
      hero: {
        headline: null;
        slides: null;
        primaryButton: string | null;
        secondaryButton: string | null;
      } | null;
      logoWall: null;
      practice: null;
      slider: null;
      recognition: null;
      influence: null;
      partners: null;
      projects: null;
      courses: null;
    }
  | {
      hero: {
        headline: string | null;
        slides: Array<{
          _key: string;
          caption: string | null;
          photo: {
            asset: {
              _id: string;
              metadata: {
                dimensions: {
                  width: number | null;
                  height: number | null;
                } | null;
              } | null;
            } | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
          } | null;
          background: {
            asset: {
              _id: string;
              metadata: {
                dimensions: {
                  width: number | null;
                  height: number | null;
                } | null;
              } | null;
            } | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
          } | null;
        }> | null;
        primaryButton: string | null;
        secondaryButton: string | null;
      } | null;
      logoWall: {
        label: string | null;
      } | null;
      practice: {
        label: string | null;
        statement: string | null;
      } | null;
      slider: {
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        }> | null;
      } | null;
      recognition: {
        label: string | null;
        heading: string | null;
        lead: string | null;
        button: string | null;
        cards: Array<{
          _key: string;
          title: string | null;
          text: string | null;
          image: {
            asset: {
              _id: string;
              metadata: {
                dimensions: {
                  width: number | null;
                  height: number | null;
                } | null;
              } | null;
            } | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            alt: string | null;
          } | null;
        }> | null;
      } | null;
      influence: {
        heading: string | null;
        lead: string | null;
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        }> | null;
        button: string | null;
      } | null;
      partners: {
        heading: string | null;
        lead: string | null;
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        }> | null;
        button: string | null;
      } | null;
      projects: {
        heading: string | null;
        lead: string | null;
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        }> | null;
        button: string | null;
      } | null;
      courses: {
        heading: string | null;
        lead: string | null;
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        }> | null;
        button: string | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: GET_IN_TOUCH_QUERY
// Query: *[_id == select($live => "live-homePage", "homePage")][0].getInTouch {  label,  title,  portrait { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },  lead,  button}
export type GET_IN_TOUCH_QUERY_RESULT = null | {
  label: string | null;
  title: string | null;
  portrait: {
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
  } | null;
  lead: string | null;
  button: string | null;
};

// Source: ../src/sanity/queries.ts
// Variable: ARCHITECTURE_PAGE_QUERY
// Query: *[_id == select($live => "live-architecturePage", "architecturePage")][0] {  header { label, heading }}
export type ARCHITECTURE_PAGE_QUERY_RESULT =
  | {
      header: null;
    }
  | {
      header: {
        label: null;
        heading: string | null;
      } | null;
    }
  | {
      header: {
        label: string | null;
        heading: string | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: INFLUENCE_PAGE_QUERY
// Query: *[_id == select($live => "live-influencePage", "influencePage")][0] {  hero { label, heading, lead, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },  reach { label, number, text },  approach { label, statement },  origins { label, heading },  insights { label, heading, lead },  atlas { label, heading },  book { label, heading, lead, button }}
export type INFLUENCE_PAGE_QUERY_RESULT =
  | {
      hero: null;
      reach: null;
      approach: null;
      origins: null;
      insights: null;
      atlas: null;
      book: null;
    }
  | {
      hero: {
        label: null;
        heading: null;
        lead: null;
        image: null;
      } | null;
      reach: null;
      approach: null;
      origins: null;
      insights: null;
      atlas: null;
      book: null;
    }
  | {
      hero: {
        label: string | null;
        heading: string | null;
        lead: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      reach: null;
      approach: null;
      origins: null;
      insights: null;
      atlas: null;
      book: null;
    }
  | {
      hero: null;
      reach: null;
      approach: null;
      origins: null;
      insights: null;
      atlas: {
        label: null;
        heading: null;
      } | null;
      book: null;
    }
  | {
      hero: {
        label: string | null;
        heading: string | null;
        lead: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      reach: {
        label: string | null;
        number: string | null;
        text: string | null;
      } | null;
      approach: {
        label: string | null;
        statement: string | null;
      } | null;
      origins: {
        label: string | null;
        heading: string | null;
      } | null;
      insights: {
        label: string | null;
        heading: string | null;
        lead: string | null;
      } | null;
      atlas: {
        label: string | null;
        heading: string | null;
      } | null;
      book: {
        label: string | null;
        heading: string | null;
        lead: string | null;
        button: string | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: SHOP_PAGE_QUERY
// Query: *[_id == select($live => "live-shopPage", "shopPage")][0] {  hero { label, heading, lead, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, primaryButton, secondaryButton },  catalogue { label, heading },  testimonials { heading, lead },  faq { label, heading, note, helpHeading, helpLead, helpButton }}
export type SHOP_PAGE_QUERY_RESULT =
  | {
      hero: null;
      catalogue: null;
      testimonials: null;
      faq: null;
    }
  | {
      hero: {
        label: null;
        heading: null;
        lead: null;
        image: null;
        primaryButton: string | null;
        secondaryButton: string | null;
      } | null;
      catalogue: null;
      testimonials: null;
      faq: null;
    }
  | {
      hero: {
        label: string | null;
        heading: string | null;
        lead: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        primaryButton: null;
        secondaryButton: null;
      } | null;
      catalogue: null;
      testimonials: null;
      faq: null;
    }
  | {
      hero: {
        label: string | null;
        heading: string | null;
        lead: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        primaryButton: string | null;
        secondaryButton: string | null;
      } | null;
      catalogue: {
        label: string | null;
        heading: string | null;
      } | null;
      testimonials: {
        heading: string | null;
        lead: string | null;
      } | null;
      faq: {
        label: string | null;
        heading: string | null;
        note: string | null;
        helpHeading: string | null;
        helpLead: string | null;
        helpButton: string | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: BOOK_PAGE_QUERY
// Query: *[_id == select($live => "live-bookPage", "bookPage")][0] {  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },  inside { heading },  atlas { caption, primaryButton, secondaryButton }}
export type BOOK_PAGE_QUERY_RESULT =
  | {
      header: null;
      overview: null;
      inside: null;
      atlas: null;
    }
  | {
      header: {
        image: null;
        heading: string | null;
        lead: null;
      } | null;
      overview: null;
      inside: null;
      atlas: null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      inside: null;
      atlas: null;
    }
  | {
      header: null;
      overview: null;
      inside: null;
      atlas: {
        caption: null;
        primaryButton: null;
        secondaryButton: null;
      } | null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      inside: {
        heading: string | null;
      } | null;
      atlas: {
        caption: string | null;
        primaryButton: string | null;
        secondaryButton: string | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: PRODUCT_PAGE_QUERY
// Query: *[_id == select($live => "live-productPage", "productPage")][0] {  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },  details { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }}
export type PRODUCT_PAGE_QUERY_RESULT =
  | {
      header: null;
      overview: null;
      details: null;
    }
  | {
      header: {
        image: null;
        heading: string | null;
        lead: null;
      } | null;
      overview: null;
      details: null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      details: null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      details: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: COURSE_COMMUNICATION_PAGE_QUERY
// Query: *[_id == select($live => "live-courseCommunicationPage", "courseCommunicationPage")][0] {  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },  details { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }}
export type COURSE_COMMUNICATION_PAGE_QUERY_RESULT =
  | {
      header: null;
      overview: null;
      details: null;
    }
  | {
      header: {
        image: null;
        heading: string | null;
        lead: null;
      } | null;
      overview: null;
      details: null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      details: null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      details: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: COURSE_SKETCHBOOK_PAGE_QUERY
// Query: *[_id == select($live => "live-courseSketchbookPage", "courseSketchbookPage")][0] {  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },  details { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }}
export type COURSE_SKETCHBOOK_PAGE_QUERY_RESULT =
  | {
      header: null;
      overview: null;
      details: null;
    }
  | {
      header: {
        image: null;
        heading: string | null;
        lead: null;
      } | null;
      overview: null;
      details: null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      details: null;
    }
  | {
      header: {
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        heading: string | null;
        lead: string | null;
      } | null;
      overview: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
      details: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: PARTNERS_PAGE_QUERY
// Query: *[_id == select($live => "live-partnersPage", "partnersPage")][0] {  intro { heading, lead, button },  clients { label, heading, note },  statement { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, lead, button },  services { label, lead },  results { label, heading, note },  enquire { label, heading, lead }}
export type PARTNERS_PAGE_QUERY_RESULT =
  | {
      intro: null;
      clients: null;
      statement: null;
      services: null;
      results: null;
      enquire: null;
    }
  | {
      intro: {
        heading: string | null;
        lead: string | null;
        button: null;
      } | null;
      clients: null;
      statement: null;
      services: null;
      results: null;
      enquire: null;
    }
  | {
      intro: {
        heading: string | null;
        lead: string | null;
        button: string | null;
      } | null;
      clients: {
        label: string | null;
        heading: string | null;
        note: string | null;
      } | null;
      statement: {
        heading: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string | null;
        } | null;
        lead: string | null;
        button: string | null;
      } | null;
      services: {
        label: string | null;
        lead: string | null;
      } | null;
      results: {
        label: string | null;
        heading: string | null;
        note: string | null;
      } | null;
      enquire: {
        label: string | null;
        heading: string | null;
        lead: string | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: PARTNERS_ARCHIVE_PAGE_QUERY
// Query: *[_id == select($live => "live-partnersArchivePage", "partnersArchivePage")][0] {  intro { heading, lead }}
export type PARTNERS_ARCHIVE_PAGE_QUERY_RESULT =
  | {
      intro: null;
    }
  | {
      intro: {
        heading: string | null;
        lead: string | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: PRIVACY_PAGE_QUERY
// Query: *[_id == select($live => "live-privacyPage", "privacyPage")][0] {  header { heading },  body}
export type PRIVACY_PAGE_QUERY_RESULT =
  | {
      header: null;
      body: null;
    }
  | {
      header: {
        heading: string | null;
      } | null;
      body: null;
    }
  | {
      header: {
        heading: string | null;
      } | null;
      body: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: TERMS_PAGE_QUERY
// Query: *[_id == select($live => "live-termsPage", "termsPage")][0] {  header { heading },  body}
export type TERMS_PAGE_QUERY_RESULT =
  | {
      header: null;
      body: null;
    }
  | {
      header: {
        heading: string | null;
      } | null;
      body: null;
    }
  | {
      header: {
        heading: string | null;
      } | null;
      body: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: PAGE_LIVE_QUERY
// Query: *[_id == $id][0]
export type PAGE_LIVE_QUERY_RESULT =
  | {
      _id: string;
      _type: "architecturePage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      header?: {
        label?: string;
        heading?: string;
      };
    }
  | {
      _id: string;
      _type: "bookPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      header?: {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        heading?: string;
        lead?: string;
      };
      overview?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
      inside?: {
        heading?: string;
      };
      atlas?: {
        caption?: string;
        primaryButton?: string;
        secondaryButton?: string;
      };
    }
  | {
      _id: string;
      _type: "client";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      logo?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      sortOrder?: number;
    }
  | {
      _id: string;
      _type: "courseCommunicationPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      header?: {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        heading?: string;
        lead?: string;
      };
      overview?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
      details?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
    }
  | {
      _id: string;
      _type: "courseSketchbookPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      header?: {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        heading?: string;
        lead?: string;
      };
      overview?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
      details?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
    }
  | {
      _id: string;
      _type: "homePage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      hero?: {
        headline?: string;
        slides?: Array<
          {
            _key: string;
          } & HeroSlide
        >;
        primaryButton?: string;
        secondaryButton?: string;
      };
      logoWall?: {
        label?: string;
      };
      practice?: {
        label?: string;
        statement?: string;
      };
      slider?: {
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
      };
      recognition?: {
        label?: string;
        heading?: string;
        lead?: string;
        button?: string;
        cards?: Array<
          {
            _key: string;
          } & HomeCard
        >;
      };
      influence?: HomeGallery;
      partners?: HomeGallery;
      projects?: HomeGallery;
      courses?: HomeGallery;
      getInTouch?: {
        label?: string;
        title?: string;
        portrait?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        lead?: string;
        button?: string;
      };
    }
  | {
      _id: string;
      _type: "influencePage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      hero?: {
        label?: string;
        heading?: string;
        lead?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
      reach?: {
        label?: string;
        number?: string;
        text?: string;
      };
      approach?: {
        label?: string;
        statement?: string;
      };
      origins?: {
        label?: string;
        heading?: string;
      };
      insights?: {
        label?: string;
        heading?: string;
        lead?: string;
      };
      atlas?: {
        label?: string;
        heading?: string;
      };
      book?: {
        label?: string;
        heading?: string;
        lead?: string;
        button?: string;
      };
    }
  | {
      _id: string;
      _type: "partnersArchivePage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      intro?: {
        heading?: string;
        lead?: string;
      };
    }
  | {
      _id: string;
      _type: "partnersPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      intro?: {
        heading?: string;
        lead?: string;
        button?: string;
      };
      clients?: {
        label?: string;
        heading?: string;
        note?: string;
      };
      statement?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        lead?: string;
        button?: string;
      };
      services?: {
        label?: string;
        lead?: string;
      };
      results?: {
        label?: string;
        heading?: string;
        note?: string;
      };
      enquire?: {
        label?: string;
        heading?: string;
        lead?: string;
      };
    }
  | {
      _id: string;
      _type: "privacyPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      header?: {
        heading?: string;
      };
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: "productPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      header?: {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        heading?: string;
        lead?: string;
      };
      overview?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
      details?: {
        heading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      };
    }
  | {
      _id: string;
      _type: "project";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      shortTitle?: string;
      slug?: Slug;
      sortOrder?: number;
      context?: string;
      year?: number;
      lead?: string;
      credits?: Array<
        {
          _key: string;
        } & ProjectCredit
      >;
      portfolio?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      portfolioUrl?: string;
      coverImage?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      content?: Array<
        | ({
            _key: string;
          } & FeatureImage)
        | ({
            _key: string;
          } & ImageGallery)
        | ({
            _key: string;
          } & TextSection)
      >;
    }
  | {
      _id: string;
      _type: "sanity.fileAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      source?: SanityAssetSourceData;
    }
  | {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    }
  | {
      _id: string;
      _type: "sanity.vercelProtectionBypass";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      secret?: string;
    }
  | {
      _id: string;
      _type: "shopPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      hero?: {
        label?: string;
        heading?: string;
        lead?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        primaryButton?: string;
        secondaryButton?: string;
      };
      catalogue?: {
        label?: string;
        heading?: string;
      };
      testimonials?: {
        heading?: string;
        lead?: string;
      };
      faq?: {
        label?: string;
        heading?: string;
        note?: string;
        helpHeading?: string;
        helpLead?: string;
        helpButton?: string;
      };
    }
  | {
      _id: string;
      _type: "termsPage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      header?: {
        heading?: string;
      };
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
    }
  | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "project" && string::startsWith(_id, "live-") == $live && defined(slug.current)] | order(sortOrder asc, _createdAt asc) {\n  _id,\n  "name": coalesce(shortTitle, title),\n  "slug": slug.current,\n  context,\n  year,\n  coverImage { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }\n}': PROJECT_INDEX_QUERY_RESULT;
    '*[_type == "project" && string::startsWith(_id, "live-") == $live && slug.current == $slug][0] {\n  _id,\n  title,\n  "name": coalesce(shortTitle, title),\n  "slug": slug.current,\n  context,\n  year,\n  lead,\n  credits[]{ _key, name, note, kind },\n  "portfolioUrl": coalesce(portfolio.asset->url, portfolioUrl),\n  content[]{\n    _key,\n    _type,\n    _type == "featureImage" => { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },\n    _type == "imageGallery" => { layout, framing, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n    _type == "textSection" => { label, body }\n  }\n}': PROJECT_PAGE_QUERY_RESULT;
    '*[_type == "client" && string::startsWith(_id, "live-") == $live && defined(logo.asset)] | order(sortOrder asc, name asc) {\n  _id,\n  name,\n  logo { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot }\n}': CLIENT_LOGOS_QUERY_RESULT;
    '*[_id == select($live => "live-homePage", "homePage")][0] {\n  hero {\n    headline,\n    slides[]{ _key, caption, photo { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot }, background { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot } },\n    primaryButton,\n    secondaryButton\n  },\n  logoWall { label },\n  practice { label, statement },\n  slider { images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n  recognition { label, heading, lead, button, cards[]{ _key, title, text, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } } },\n  influence { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button },\n  partners { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button },\n  projects { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button },\n  courses { heading, lead, images[]{ _key, asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, button }\n}': HOME_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-homePage", "homePage")][0].getInTouch {\n  label,\n  title,\n  portrait { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },\n  lead,\n  button\n}': GET_IN_TOUCH_QUERY_RESULT;
    '*[_id == select($live => "live-architecturePage", "architecturePage")][0] {\n  header { label, heading }\n}': ARCHITECTURE_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-influencePage", "influencePage")][0] {\n  hero { label, heading, lead, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n  reach { label, number, text },\n  approach { label, statement },\n  origins { label, heading },\n  insights { label, heading, lead },\n  atlas { label, heading },\n  book { label, heading, lead, button }\n}': INFLUENCE_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-shopPage", "shopPage")][0] {\n  hero { label, heading, lead, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, primaryButton, secondaryButton },\n  catalogue { label, heading },\n  testimonials { heading, lead },\n  faq { label, heading, note, helpHeading, helpLead, helpButton }\n}': SHOP_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-bookPage", "bookPage")][0] {\n  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },\n  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n  inside { heading },\n  atlas { caption, primaryButton, secondaryButton }\n}': BOOK_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-productPage", "productPage")][0] {\n  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },\n  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n  details { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }\n}': PRODUCT_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-courseCommunicationPage", "courseCommunicationPage")][0] {\n  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },\n  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n  details { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }\n}': COURSE_COMMUNICATION_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-courseSketchbookPage", "courseSketchbookPage")][0] {\n  header { image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, heading, lead },\n  overview { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n  details { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }\n}': COURSE_SKETCHBOOK_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-partnersPage", "partnersPage")][0] {\n  intro { heading, lead, button },\n  clients { label, heading, note },\n  statement { heading, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, lead, button },\n  services { label, lead },\n  results { label, heading, note },\n  enquire { label, heading, lead }\n}': PARTNERS_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-partnersArchivePage", "partnersArchivePage")][0] {\n  intro { heading, lead }\n}': PARTNERS_ARCHIVE_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-privacyPage", "privacyPage")][0] {\n  header { heading },\n  body\n}': PRIVACY_PAGE_QUERY_RESULT;
    '*[_id == select($live => "live-termsPage", "termsPage")][0] {\n  header { heading },\n  body\n}': TERMS_PAGE_QUERY_RESULT;
    "*[_id == $id][0]": PAGE_LIVE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
